import colorcet as cc
import folium
import geopandas as gpd
from shapely.geometry import box
from streamlit_folium import st_folium

from database import LOCATIONS_TABLE
from modules.database import get_table

LOCATIONS = get_table(LOCATIONS_TABLE)


def overview_map(map_style):
    """
    Overview map on the "Home" page

    :param map_style: User selected map style

    :return:
        st_folium() map object
    """
    glacier_sites = gpd.GeoDataFrame(
        LOCATIONS.execute(), geometry="geometry", crs="EPSG:4326"
    )
    map = folium.Map(location=[72, -40], zoom_start=4, tiles=map_style)

    # Add markers to signify study sites:
    tooltip = folium.GeoJsonTooltip(
        fields=["Official_name"],
        aliases=["Name"],
        localize=True,
        sticky=False,
        labels=True,
        style="""
            background-color: #F0EFEF;
            border: 2px solid black;
            border-radius: 3px;
            box-shadow: 3px;
        """,
        max_width=400,
    )
    folium.GeoJson(
        glacier_sites,
        name="Iceberg Study Sites",
        marker=folium.Marker(icon=folium.Icon(icon="star")),
        tooltip=tooltip,
    ).add_to(map)

    return st_folium(
        map, use_container_width=True, returned_objects=["last_active_drawing"]
    )


def last_viewed_site(map_click):
    map_click = map_click.get("last_active_drawing", {})
    if map_click:
        return map_click.get("properties", {}).get("Glacier_ID")
    else:
        return None


def shape_color(map_element, color_map: dict) -> dict:
    """
    Select a unique color for each iceberg from the color map.

    :param map_element: Map element to render
    :param color_map: Unique colors of all icebergs generated by :py:func:`unique_colors`

    :return:
        Dictionary with style settings for the map element
    """
    iceberg_id = map_element["properties"]["IcebergID"]
    # Show the date combinations with different styles. The early date has 0 as date_rank
    if map_element["properties"]["date_rank"] == 0:
        line_color = "black"
        opacity = 0.7
        weight = 1
    else:
        line_color = "darkgray"
        opacity = 0.6
        weight = 2

    return {
        "color": line_color,
        "fillColor": color_map.get(iceberg_id, "#808080"),
        "weight": weight,
        "fillOpacity": opacity,
    }


def unique_colors(iceberg_sites: gpd.GeoDataFrame) -> dict:
    """
    Create a unique color for each iceberg

    :param iceberg_sites: GeoDataFrame with icebergs

    :return:
        Dictionary with unique colors for each iceberg
    """
    iceberg_ids = iceberg_sites["IcebergID"].unique()
    palette = cc.glasbey[: len(iceberg_ids)]
    return {ice_id: palette[index] for index, ice_id in enumerate(iceberg_ids)}


def iceberg_map(iceberg_sites: gpd.GeoDataFrame):
    """
    Create map with icebergs shapes

    :param iceberg_sites: GeoDataFrame with icebergs to show in the map

    :return:
        Folium map object
    """
    iceberg_sites.to_crs("EPSG:4326", inplace=True)

    map_center = box(*iceberg_sites.total_bounds).centroid
    map_element = folium.Map(
        location=[map_center.y, map_center.x], zoom_start=11, tiles="CartoDB positron"
    )

    tooltip = folium.GeoJsonTooltip(
        fields=["observed_date", "IcebergID"],
        aliases=["Date", "Iceberg ID"],
        localize=True,
        sticky=False,
        labels=True,
        style="""
            background-color: #F0EFEF;
            border: 2px solid black;
            border-radius: 3px;
            box-shadow: 3px;
        """,
    )

    shape_colors = unique_colors(iceberg_sites)
    folium.GeoJson(
        iceberg_sites,
        style_function=lambda x: shape_color(x, shape_colors),
        tooltip=tooltip,
    ).add_to(map_element)

    return map_element
