name: ice_age
channels:
  - conda-forge
dependencies:
  - duckdb
  - geopandas
  - ibis-duckdb
  - ibis-framework
  - python-graphviz
  - seaborn
  - shapely[version=">=2,<3"]
  - streamlit
  - streamlit-folium
